Update pipeline to increase gstreamer performance
AMWA-TV/nmos-sender-receiver-framework pull request #10
Opened 2024-09-19 15:22 UTC by joaofigueiredobisect

2024-09-19 17:10 UTC, pedro-alves-ferreira requested changes

2024-09-19 17:10 UTC, pedro-alves-ferreira commented on cpp/libs/ossrf_gstreamer_api/lib/src/receiver/st2110_20_receiver_plugin.cpp
>          // Add pipeline queue1
I don't think it's a good idea to remove the jitter buffer.

2024-09-19 17:10 UTC, pedro-alves-ferreira commented on cpp/libs/ossrf_gstreamer_api/lib/src/receiver/st2110_20_receiver_plugin.cpp
> +        g_object_set(queue1, "max-size-buffers", 3, NULL);
`queue1` handles RTP buffers, while `queue2` handles full frames. Each frame may have several thousands of packets, so I don't think it is a good idea to use the same value (3) for both.
Probably the best solution is to work based on time, for example, you could set both to 200 ms.
Also, make sure you set `max-size-time`, `max-size-buffers` and `max-size-bytes`. They all have defaults and we probably don't want to rely on them. If we go with my suggestion (using `max-size-time`), then we should set both `max-size-buffers` and `max-size-bytes` to `0`, in order to disable those checks and rely only on time.

2024-09-19 17:10 UTC, pedro-alves-ferreira commented on cpp/libs/ossrf_gstreamer_api/lib/src/receiver/st2110_20_receiver_plugin.cpp
> +        g_object_set(queue1, "max-size-buffers", 3, NULL);
Don't hardcode constants in a function call (3 in this case). Always define `constexpr` values with meaningful names and explain why you chose that value.

2024-09-20 09:58 UTC, pedro-alves-ferreira approved these changes
LGTM

2024-09-20 10:06 UTC, massis08 approved these changes
LGTM

2024-09-20 10:07 UTC, merged