Jf/dev/update docker user
AMWA-TV/nmos-sender-receiver-framework pull request #14
Opened 2024-09-24 13:13 UTC by joaofigueiredobisect

2024-09-24 13:24 UTC, peterbrightwell approved these changes
Looks right

2024-09-25 08:46 UTC, massis08 commented on README.md
Add to the readme an explanation of how it is possible to map a .conan2 folder in order to have persistent data storage.

2024-09-25 14:43 UTC, massis08 approved these changes
LGTM

2024-09-26 08:08 UTC, pedro-alves-ferreira requested changes

2024-09-26 08:08 UTC, pedro-alves-ferreira commented on README.md
> +This project includes a development container to facilitate code development. When the container is built for the first time, it is empty, and the repository needs to be downloaded again inside the c
How about "cloned again" rather than "downloaded again"?

2024-09-26 08:08 UTC, pedro-alves-ferreira commented on README.md
> +The password for the username is:
The password for this user is

2024-09-26 08:08 UTC, pedro-alves-ferreira commented on README.md
> +- You can map an outside of the container .conan2 folder in order to have persistent data storage. You just need to add the bellow line on to the volumes inside the docker-compose-x86-development.yml
"below", not "bellow"

2024-09-30 10:26 UTC, pedro-alves-ferreira approved these changes
LGTM

2024-09-30 10:28 UTC, merged