Associate devices with added senders and receivers
AMWA-TV/nmos-sender-receiver-framework pull request #4
Opened 2024-09-09 13:45 UTC by joaofigueiredobisect

2024-09-09 14:02 UTC, pedro-alves-ferreira approved these changes
LGTM

2024-09-09 14:05 UTC, massis08 requested changes

2024-09-09 14:05 UTC, massis08 commented on cpp/libs/ossrf_nmos_api/lib/src/resources/nmos_resource_sender.cpp
> +}
Here you want to return nmos::types::sender and not receiver

2024-09-10 14:26 UTC, massis08 approved these changes
LGTM

2024-09-10 15:08 UTC, merged